# NUMPY

In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:

#You can easily check that a newly created object is an ndarray by passing 
#the new variable to the type() function.

type(arr)

numpy.ndarray

In [7]:
arr.dtype

dtype('int32')

In [9]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

1
(3,)
3


In [10]:
# for 2D array

my_list = [[1,2,3],[4,5,6],[7,8,9]] # lists within list
arr = np.array(my_list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int32
2
(3, 3)
9


In [12]:
my_list = [[1,2,3,4],[4,5,6,7],[7,8,9,10]]
arr = np.array(my_list)
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [13]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int32
2
(3, 4)
12


In [18]:
my_list = [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]]*3
arr = np.array(my_list)
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

In [19]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int32
3
(3, 3, 4)
36


In [20]:
arr.itemsize

4

In [21]:
arr.data

In [26]:
arr = np.array(my_list, dtype = complex)
arr

array([[[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
        [ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j],
        [ 7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j]],

       [[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
        [ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j],
        [ 7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j]],

       [[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
        [ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j],
        [ 7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j]]])

# Intrinsic creation of array 

In [27]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4,20,3)

array([ 4,  7, 10, 13, 16, 19])

In [30]:
np.arange(0,1,0.1) # we mention the step here

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [47]:
np.linspace(0,1,20)  # divides the period 0 to 1 into 20 parts 

# linespace()- defines the number of elements into which we want the interval 
# to be split.

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [37]:
np.arange(0,1,0.1).reshape(2,5) # converted to 2D array

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [39]:
np.arange(0,1,0.1).reshape(2,1,5) # converted to 3D array

array([[[0. , 0.1, 0.2, 0.3, 0.4]],

       [[0.5, 0.6, 0.7, 0.8, 0.9]]])

In [38]:
np.linspace(0,1,10).reshape(2,5)

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

In [42]:
np.zeros((3,3), dtype= int) # default is float

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
np.ones((3,4)) # deafult is float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.random.random((3,3))
# This is possible using the random() function of the numpy.random module

array([[0.21783714, 0.55450945, 0.58496528],
       [0.28396268, 0.92081901, 0.10451746],
       [0.43504551, 0.9861899 , 0.13855314]])

In [53]:
np.random.random(3)

array([0.26670222, 0.65816312, 0.72257621])

In [49]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
print(np.random.rand(5))# gives numbers from a uniform dist.
print(np.random.randn(5)) # gives numbers from a std. normal dist.

[0.83178144 0.92303681 0.29867213 0.91004854 0.50849996]
[0.59988131 2.47648511 0.0677572  0.34451491 0.07035611]


In [57]:
np.random.randint(1,100) 
# you get a random integer between 1(inclusive) and 100(exclusive)

23

In [58]:
np.random.randint(1,100,10) # to get 10 random integers

array([53, 24, 37, 30, 31, 77, 52, 47, 21, 38])

In [62]:
arr = np.random.randint(0,50,10)
print(arr)
arr.max()

[ 9 41 32 18  1 12 22 37 47 11]


47

In [63]:
arr.min()

1

In [65]:
arr.argmax()

8

In [66]:
arr.argmin()

4

In [67]:
# another way of random numbers 

from numpy.random import randint

randint(2,10,5)

array([3, 8, 5, 5, 3])

# Indexing

In [70]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [71]:
a[4] # the element in index 4 i.e. the 5th element 

14

In [74]:
a[-1]

15

In [75]:
a[[1,3,4]]

array([11, 13, 14])

In [77]:
A = np.arange(10, 22).reshape((3, 4))
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [78]:
# If you want to remove the element of the third column in the second row ie.16

A[1,2]  # since the count starts from zero , clearly the 1st row is [0,] , 
# 2nd row is [1,].... while ist coloumn is [,0] , 2nd coloumn is [,1]....

16

In [79]:
A[1,]  # gives the 2nd row elements

array([14, 15, 16, 17])

# Slicing

In [80]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [81]:
a[1:3] # excludes the last index

array([11, 12])

In [82]:
a[-3:-1]

array([13, 14])

In [85]:
a[1:]

array([11, 12, 13, 14, 15])

In [86]:
a[1::2]  # 3rd argument is the step 

array([11, 13, 15])

In [87]:
a[::2]

array([10, 12, 14])

In [88]:
a[:-1:2]   

array([10, 12, 14])

In [89]:
A = np.arange(10, 22).reshape((3, 4))
A

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [98]:
print(A[0,:])
print(A[0,:].ndim)

print(A[0:1,0:])
print(A[0:1,0:].ndim)

[10 11 12 13]
1
[[10 11 12 13]]
2


In [91]:
A[:,0]

array([10, 14, 18])

In [93]:
A[0:3 , 0:2]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [94]:
# If the indexes of the rows or columns to be extracted are not contiguous,
#  you can specify an array of indexes.

A[[0,2],0:2]

array([[10, 11],
       [18, 19]])

In [103]:
# note:

arr = np.arange(0,10)
print(arr)
slice_arr = arr[1:5]
slice_arr[:] = 3
print(slice_arr)
print(arr)  # original array gets changed

[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3]
[0 3 3 3 3 5 6 7 8 9]


In [105]:
arr = np.arange(0,10)
print(arr)
slice_arr = arr.copy()
slice_arr[1:5] = 3
print(slice_arr)
print(arr)  # original array does not get changed

[0 1 2 3 4 5 6 7 8 9]
[0 3 3 3 3 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


# Iterating an Array

In [108]:
arr = np.arange(1,6)

In [109]:
for i in arr:
    print(i)

1
2
3
4
5


In [110]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [111]:
for r in A:
    print(r)

[10 11 12]
[13 14 15]
[16 17 18]


In [112]:
for r in A.flat:   # element by element operation in a 2D array
    print(r)

10
11
12
13
14
15
16
17
18


In [114]:
np.apply_along_axis(np.mean, axis =0 , arr=A, dtype = int)

array([13, 14, 15])

In [125]:
np.apply_along_axis(np.mean, axis =1 , arr=A, dtype = int)

array([11, 14, 17])

In [123]:
np.apply_over_axes(np.mean, A , [0]) # gives a 2D array

array([[13., 14., 15.]])

In [126]:
np.apply_over_axes(np.mean, A , [1])

array([[11.],
       [14.],
       [17.]])

In [127]:
np.apply_over_axes(np.mean, A , [0,1]) # total mean of all elements

array([[14.]])

In [134]:
def foo(x):
    return x/2

np.apply_along_axis(foo, axis =0 , arr=A)


array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [135]:
np.apply_along_axis(foo, axis =1 , arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

# Conditions and Boolean Arrays

In [138]:
arr = np.random.randn(20)
arr

array([-1.41621521,  0.06743392,  0.46820091,  1.22623354,  1.10347669,
       -1.16565978,  1.86639194, -0.14472576, -1.27991796, -1.54314592,
        0.22859067, -1.51021307, -0.14289732, -1.88482673,  0.07911638,
       -1.14134005,  0.1763472 ,  0.66230376, -0.53400124, -0.24424667])

In [139]:
arr > 0

array([False,  True,  True,  True,  True, False,  True, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
       False, False])

In [140]:
arr[arr>0]

array([0.06743392, 0.46820091, 1.22623354, 1.10347669, 1.86639194,
       0.22859067, 0.07911638, 0.1763472 , 0.66230376])

# Shape Manipulation

In [143]:
a = np.random.random(12)
print (a)
A = a.reshape(3,4)
A

[0.77405906 0.49715741 0.14380285 0.17332844 0.79005209 0.20053938
 0.10864419 0.67666841 0.65537305 0.30788926 0.77398245 0.65550084]


array([[0.77405906, 0.49715741, 0.14380285, 0.17332844],
       [0.79005209, 0.20053938, 0.10864419, 0.67666841],
       [0.65537305, 0.30788926, 0.77398245, 0.65550084]])

In [144]:
a.shape = (3,4)
a

array([[0.77405906, 0.49715741, 0.14380285, 0.17332844],
       [0.79005209, 0.20053938, 0.10864419, 0.67666841],
       [0.65537305, 0.30788926, 0.77398245, 0.65550084]])

In [146]:
a = a.ravel()
a

array([0.77405906, 0.49715741, 0.14380285, 0.17332844, 0.79005209,
       0.20053938, 0.10864419, 0.67666841, 0.65537305, 0.30788926,
       0.77398245, 0.65550084])

In [148]:
a.shape = (12)
a

array([0.77405906, 0.49715741, 0.14380285, 0.17332844, 0.79005209,
       0.20053938, 0.10864419, 0.67666841, 0.65537305, 0.30788926,
       0.77398245, 0.65550084])

In [149]:
a.shape = (3,4)
a

array([[0.77405906, 0.49715741, 0.14380285, 0.17332844],
       [0.79005209, 0.20053938, 0.10864419, 0.67666841],
       [0.65537305, 0.30788926, 0.77398245, 0.65550084]])

In [150]:
a.transpose()

array([[0.77405906, 0.79005209, 0.65537305],
       [0.49715741, 0.20053938, 0.30788926],
       [0.14380285, 0.10864419, 0.77398245],
       [0.17332844, 0.67666841, 0.65550084]])

# Basic Operations 

In [5]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [6]:
a+4  # Recycling property just like R programming 

array([4, 5, 6, 7])

In [7]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [8]:
a+b  # element wise operation

array([ 4,  6,  8, 10])

In [21]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3), dtype = "int")

In [22]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
B

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
A+B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
A*B  # element wise operation , not a matrix product 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
matrix_product = np.dot(A,B)
matrix_product

array([[ 3,  3,  3],
       [12, 12, 12],
       [21, 21, 21]])

In [28]:
A.dot(B)  # alternate way for matrix product

array([[ 3,  3,  3],
       [12, 12, 12],
       [21, 21, 21]])

In [27]:
matrix_product = np.dot(B,A)
matrix_product

array([[ 9, 12, 15],
       [ 9, 12, 15],
       [ 9, 12, 15]])

In [29]:
A+=1  # increment operator 

In [30]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
B-=1
B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
M = np.ones((4,4))

for i in range(4):
    for j in range(4):
        if i != j:
            M[i,j] = 0
        else:
            break
print(M)

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [42]:
M = np.ones((4,4))

for i in range(3,-1,-1):
    for j in range(3,-1,-1):
        if i != j:
            M[i,j] = 0
        else:
            break
print(M)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [41]:
list(range(3,-1,-1)) # reason for the above for loop

[3, 2, 1, 0]

In [43]:
M = np.ones((4,4))

for i in range(4):
    for j in range(4):
        if i != j:
            M[i,j] = 0
        else:
            continue 
print(M)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
a = np.arange(1, 5)

np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [47]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [49]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [50]:
np.sum(a)

10

In [51]:
np.max(a)

4

In [52]:
np.min(a)

1

In [53]:
np.mean(a)

2.5

In [54]:
np.std(a)

1.118033988749895

# Array Manipulation

In [55]:
A = np.ones((3,3))
B = np.zeros((3,3))

C = np.vstack((A,B))
C

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
C = np.hstack((A,B))
C

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [57]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))  # more like cbind() in R programming 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [58]:
np.row_stack((a, b, c)) # more like rbind() in R programming

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Splitting Arrays

In [59]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
[B,C] = np.vsplit(A,2)

In [62]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
[B,C] = np.hsplit(A,2)

In [65]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [66]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [67]:
[B,C,D] = np.split(A,[2,3], axis = 1)

In [68]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [69]:
C

array([[ 2],
       [ 6],
       [10],
       [14]])

In [70]:
D

array([[ 3],
       [ 7],
       [11],
       [15]])

In [71]:
[B,C,D] = np.split(A,[2,3], axis = 0) # axis = 0 means rows 

In [72]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
C

array([[ 8,  9, 10, 11]])

In [74]:
D

array([[12, 13, 14, 15]])

In [75]:
# using split() to do hsplit()

[B,C] = np.split(A, [2], axis =0)

In [76]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [77]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
# same can also be done for vsplit()

[B,C] = np.split(A, [2], axis =1)

In [79]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [80]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# General Concepts

## Copies or Views of Objects

In [82]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [83]:
b = a

In [84]:
a[2] = 0

In [85]:
b

array([0, 1, 0, 3, 4])

In [89]:
c= a[0:3]
c

array([ 0,  1, 99])

In [90]:
a[2] = 99

In [92]:
c

array([ 0,  1, 99])

In [93]:
a

array([ 0,  1, 99,  3,  4])

In [94]:
c = a.copy()
c

array([ 0,  1, 99,  3,  4])

In [95]:
a[2] = 86
a

array([ 0,  1, 86,  3,  4])

In [96]:
c

array([ 0,  1, 99,  3,  4])

## Vectorization

## Broadcasting

In [98]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
B = np.arange(4) 
B

array([0, 1, 2, 3])

In [100]:
A+B

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [101]:
m = np.arange(6).reshape(3, 1, 2)
n = np.arange(6).reshape(3, 2, 1)

In [102]:
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [103]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [104]:
m+n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

## Structured Arrays

In [105]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,
2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [106]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j),
(3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))

structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [107]:
structured[1]

(2, b'Second', 1.3, 2.-2.j)

In [109]:
structured['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [110]:
structured['f3']

array([1.+2.j, 2.-2.j, 1.+3.j], dtype=complex64)

In [111]:
structured = np.array([(1,'First',0.5,1+2j),(2,'Second',1.3,2-2j),
(3,'Third',0.8,1+3j)],dtype=[('id','i2'),('position','a6'),
                             ('value','f4'),('complex','c8')])

structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [112]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,
2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))

structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [116]:
structured.dtype.names = ('id', 'order', 'value', 'complex')

In [117]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('order', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [119]:
structured['order']

array([b'First', b'Second', b'Third'], dtype='|S6')