## pandas in Depth: Data Manipulation

### Merging

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})

frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [5]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})

frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [6]:
pd.merge(frame1, frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

As you can see from the result, the returned dataframe consists of all rows that have
an ID in common. In addition to the common column, the columns from the first and
the second dataframe are added.
In this case, you used the merge() function without specifying any column explicitly.
In fact, in most cases you need to decide which is the column on which to base the
merging.

 To do this, add the on option with the column name as the key for the merging.

In [7]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [8]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [9]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [10]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [11]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

As expected, the results vary considerably depending on the criteria of merging.
Often, however, the opposite problem arises, that is, to have two dataframes in which
the key columns do not have the same name. To remedy this situation, you have to use
the left_on and right_on options, which specify the key column for the first and for the
second dataframe. Now you can see an example.

In [12]:
frame2.columns = ['brand','sid']

In [13]:
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [15]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [17]:
pd.merge(frame1, frame2, left_on='brand', right_on='sid')

id  color brand_x brand_y  sid
0     ball  white     OMG  pencil  OMG
1   pencil    red     ABC    ball  ABC
2      pen    red     ABC    ball  ABC
3      mug  black     POD  pencil  POD
4      mug  black     POD     pen  POD
5  ashtray  green     POD  pencil  POD
6  ashtray  green     POD     pen  POD

By default, the merge() function performs an inner join; the keys in the result are the
result of an intersection.
Other possible options are the left join, the right join, and the outer join. The outer
join produces the union of all keys, combining the effect of a left join with a right join. To
select the type of join you have to use the how option.

In [21]:
frame2.columns = ['id','brand']

In [22]:
frame1


id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [23]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [24]:
pd.merge(frame1, frame2, on = 'id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [32]:
pd.merge(frame1, frame2, on = 'id', how = 'outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [31]:
pd.merge(frame1, frame2, on = 'id', how = 'left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [30]:
pd.merge(frame1, frame2, on = 'id', how = 'right')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [33]:
# To merge multiple keys, you simply add a list to the on option.

pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD
5   pencil    NaN   OMG
6   pencil    NaN   POD
7     ball    NaN   ABC
8      pen    NaN   POD

#### Merging on an Index

In some cases, instead of considering the columns of a dataframe as keys, indexes could
be used as keys for merging. Then in order to decide which indexes to consider, you
set the left_index or right_index options to True to activate them, with the ability to
activate them both

In [34]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

But the dataframe objects have a join() function, which is much more convenient
when you want to do the merging by indexes. It can also be used to combine many
dataframe objects having the same or the same indexes but with no columns overlapping

In [37]:
frame1.join(frame2)
#You will get an error code because some columns in frame1 have the same 
#name as frame2. Then rename the columns in frame2 before launching the 
#join() function.

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [39]:
frame2.columns = ['id2','brand2']

frame1.join(frame2)

id  color brand     id2 brand2
0     ball  white   OMG  pencil    OMG
1   pencil    red   ABC  pencil    POD
2      pen    red   ABC    ball    ABC
3      mug  black   POD     pen    POD
4  ashtray  green   POD     NaN    NaN

Here you've performed a merge, but based on the values of the indexes instead of
the columns. This time there is also the index 4 that was present only in frame1, but the
values corresponding to the columns of frame2 report NaN as a value

### Concatenating

Another type of data combination is referred to as concatenation. NumPy provides a
concatenate() function to do this kind of operation with arrays.

In [3]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [6]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

With the pandas library and its data structures like series and dataframe, having
labeled axes allows you to further generalize the concatenation of arrays. The concat()
function is provided by pandas for this kind of operation.

In [7]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.662951
2    0.414558
3    0.835570
4    0.724717
dtype: float64

In [8]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.491675
6    0.195278
7    0.930374
8    0.004403
dtype: float64

In [9]:
pd.concat([ser1,ser2])

1    0.662951
2    0.414558
3    0.835570
4    0.724717
5    0.491675
6    0.195278
7    0.930374
8    0.004403
dtype: float64

By default, the concat() function works on axis = 0, having as a returned object a
series. If you set the axis = 1, then the result will be a dataframe.

In [10]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.662951       NaN
2  0.414558       NaN
3  0.835570       NaN
4  0.724717       NaN
5       NaN  0.491675
6       NaN  0.195278
7       NaN  0.930374
8       NaN  0.004403

The problem with this kind of operation is that the concatenated parts are not
identifiable in the result. For example, you want to create a hierarchical index on the axis
of concatenation. To do this, you have to use the keys option

In [11]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.662951
   2    0.414558
   3    0.835570
   4    0.724717
2  5    0.491675
   6    0.195278
   7    0.930374
   8    0.004403
dtype: float64